-- Migration 0022: Sprint 34 New Tables
-- DVI, Digital Signatures, Marketing, Fleet, Loyalty, Google Reviews
-- Auto-generated by AutomotiveOS Cloud ERP

BEGIN;

-- ─── Sucursales (Multi-branch) ──────────────
CREATE TABLE IF NOT EXISTS sucursales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_slug VARCHAR(100) NOT NULL,
  nombre VARCHAR(200) NOT NULL,
  codigo VARCHAR(20) NOT NULL,
  direccion TEXT,
  telefono VARCHAR(50),
  email VARCHAR(200),
  gerente_nombre VARCHAR(200),
  horario_apertura TIME DEFAULT '07:30',
  horario_cierre TIME DEFAULT '17:30',
  capacidad_bahias INTEGER DEFAULT 5,
  activa BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sucursales_tenant ON sucursales(tenant_slug);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sucursales_codigo_tenant ON sucursales(codigo, tenant_slug);

-- ─── DVI Inspections ────────────────────────
CREATE TABLE IF NOT EXISTS dvi_inspections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  orden_trabajo_id UUID NOT NULL,
  health_score INTEGER DEFAULT 100,
  inspector_nombre VARCHAR(200),
  observaciones TEXT,
  tenant_slug VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_dvi_orden ON dvi_inspections(orden_trabajo_id);
CREATE INDEX IF NOT EXISTS idx_dvi_tenant ON dvi_inspections(tenant_slug);

-- ─── DVI Photos ─────────────────────────────
CREATE TABLE IF NOT EXISTS dvi_photos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inspection_id UUID NOT NULL REFERENCES dvi_inspections(id) ON DELETE CASCADE,
  photo_url TEXT NOT NULL,
  markup_data JSONB DEFAULT '[]',
  caption VARCHAR(500),
  tenant_slug VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_dvi_photos_inspection ON dvi_photos(inspection_id);

-- ─── DVI Items ──────────────────────────────
CREATE TABLE IF NOT EXISTS dvi_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inspection_id UUID NOT NULL REFERENCES dvi_inspections(id) ON DELETE CASCADE,
  nombre VARCHAR(200) NOT NULL,
  categoria VARCHAR(50) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'ok' CHECK (estado IN ('ok', 'atencion', 'critico', 'na')),
  observaciones TEXT,
  tenant_slug VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_dvi_items_inspection ON dvi_items(inspection_id);

-- ─── Digital Signatures ─────────────────────
CREATE TABLE IF NOT EXISTS digital_signatures (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  orden_trabajo_id UUID NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  firma_base64 TEXT NOT NULL,
  cliente_nombre VARCHAR(255),
  cliente_documento VARCHAR(50),
  observaciones TEXT,
  tenant_slug VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sig_orden ON digital_signatures(orden_trabajo_id);
CREATE INDEX IF NOT EXISTS idx_sig_tenant ON digital_signatures(tenant_slug);

-- ─── Marketing Campaigns ────────────────────
CREATE TABLE IF NOT EXISTS marketing_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_slug VARCHAR(100) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('whatsapp', 'email', 'sms')),
  mensaje TEXT NOT NULL,
  programada_at TIMESTAMPTZ,
  enviada_at TIMESTAMPTZ,
  estado VARCHAR(20) NOT NULL DEFAULT 'borrador' CHECK (estado IN ('borrador', 'programada', 'activa', 'completada', 'cancelada')),
  segmento VARCHAR(100),
  total_enviados INTEGER DEFAULT 0,
  total_exitosos INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_campaigns_tenant ON marketing_campaigns(tenant_slug);
CREATE INDEX IF NOT EXISTS idx_campaigns_estado ON marketing_campaigns(estado);

-- ─── Fleets (B2B) ──────────────────────────
CREATE TABLE IF NOT EXISTS fleets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_slug VARCHAR(100) NOT NULL,
  nombre VARCHAR(200) NOT NULL,
  empresa VARCHAR(200),
  contacto_nombre VARCHAR(200),
  contacto_telefono VARCHAR(50),
  contacto_email VARCHAR(200),
  contrato_activo BOOLEAN DEFAULT TRUE,
  contrato_inicio DATE,
  contrato_fin DATE,
  descuento_porcentaje NUMERIC(5,2) DEFAULT 0,
  notas TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fleets_tenant ON fleets(tenant_slug);

-- ─── Fleet Vehicles ─────────────────────────
CREATE TABLE IF NOT EXISTS fleet_vehicles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  fleet_id UUID NOT NULL REFERENCES fleets(id) ON DELETE CASCADE,
  vehiculo_id UUID NOT NULL,
  placa VARCHAR(20),
  marca VARCHAR(100),
  modelo VARCHAR(100),
  anio INTEGER,
  tenant_slug VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fleet_vehicles_fleet ON fleet_vehicles(fleet_id);
CREATE INDEX IF NOT EXISTS idx_fleet_vehicles_vehiculo ON fleet_vehicles(vehiculo_id);

-- ─── Loyalty Accounts ──────────────────────
CREATE TABLE IF NOT EXISTS loyalty_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_slug VARCHAR(100) NOT NULL,
  cliente_id UUID NOT NULL,
  puntos INTEGER DEFAULT 0,
  tier VARCHAR(20) NOT NULL DEFAULT 'BRONCE' CHECK (tier IN ('BRONCE', 'PLATA', 'ORO', 'PLATINO')),
  total_puntos_ganados INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_loyalty_tenant ON loyalty_accounts(tenant_slug);
CREATE INDEX IF NOT EXISTS idx_loyalty_cliente ON loyalty_accounts(cliente_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_loyalty_cliente_tenant ON loyalty_accounts(cliente_id, tenant_slug);

-- ─── Loyalty Transactions ──────────────────
CREATE TABLE IF NOT EXISTS loyalty_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_slug VARCHAR(100) NOT NULL,
  cliente_id UUID NOT NULL,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('ganado', 'canjeado', 'expirado', 'ajuste')),
  puntos INTEGER NOT NULL,
  descripcion TEXT,
  referencia_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_loyalty_tx_tenant ON loyalty_transactions(tenant_slug);
CREATE INDEX IF NOT EXISTS idx_loyalty_tx_cliente ON loyalty_transactions(cliente_id);

-- ─── Loyalty Rewards ────────────────────────
CREATE TABLE IF NOT EXISTS loyalty_rewards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_slug VARCHAR(100) NOT NULL,
  nombre VARCHAR(200) NOT NULL,
  descripcion TEXT,
  puntos_requeridos INTEGER NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  activa BOOLEAN DEFAULT TRUE,
  stock INTEGER DEFAULT -1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_loyalty_rewards_tenant ON loyalty_rewards(tenant_slug);

-- ─── Google Reviews ─────────────────────────
CREATE TABLE IF NOT EXISTS google_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_slug VARCHAR(100) NOT NULL,
  reviewer_name VARCHAR(200),
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  review_date TIMESTAMPTZ,
  sentiment VARCHAR(20),
  responded BOOLEAN DEFAULT FALSE,
  response_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_reviews_tenant ON google_reviews(tenant_slug);
CREATE INDEX IF NOT EXISTS idx_reviews_rating ON google_reviews(rating);

-- ─── Marketing Campaign Recipients ──────────
CREATE TABLE IF NOT EXISTS campaign_recipients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id UUID NOT NULL REFERENCES marketing_campaigns(id) ON DELETE CASCADE,
  cliente_id UUID NOT NULL,
  telefono VARCHAR(50),
  email VARCHAR(200),
  estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'enviado', 'entregado', 'error')),
  enviado_at TIMESTAMPTZ,
  error_mensaje TEXT,
  tenant_slug VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_campaign_recipients_campaign ON campaign_recipients(campaign_id);

COMMIT;
