-- Migration 0024: Data integrity CHECK constraints
-- Auto-generated from Drizzle schema files
--
-- Adds CHECK constraints for monetary amounts, percentages, stock,
-- and domain ranges across all tables.
--

ALTER TABLE "activos_fijos" ADD CONSTRAINT "activos_fijos_costoAdquisicion_check" CHECK ("activos_fijos"."costo_adquisicion" >= 0);
ALTER TABLE "asientos_contables" ADD CONSTRAINT "asientos_contables_totalDebe_check" CHECK ("asientos_contables"."total_debe" >= 0);
ALTER TABLE "asientos_contables" ADD CONSTRAINT "asientos_contables_totalHaber_check" CHECK ("asientos_contables"."total_haber" >= 0);
ALTER TABLE "asientos_detalle" ADD CONSTRAINT "asientos_detalle_debe_check" CHECK ("asientos_detalle"."debe" >= 0);
ALTER TABLE "asientos_detalle" ADD CONSTRAINT "asientos_detalle_haber_check" CHECK ("asientos_detalle"."haber" >= 0);
ALTER TABLE "backup_jobs" ADD CONSTRAINT "backup_jobs_fileSize_check" CHECK ("backup_jobs"."file_size" >= 0);
ALTER TABLE "backup_jobs" ADD CONSTRAINT "backup_jobs_duracionMs_check" CHECK ("backup_jobs"."duracion_ms" >= 0);
ALTER TABLE "backup_jobs" ADD CONSTRAINT "backup_jobs_progreso_check" CHECK ("backup_jobs"."progreso" BETWEEN 0 AND 100);
ALTER TABLE "backup_policies" ADD CONSTRAINT "backup_policies_horaEjecucion_check" CHECK ("backup_policies"."hora_ejecucion" >= 0 AND "backup_policies"."hora_ejecucion" <= 23);
ALTER TABLE "backup_policies" ADD CONSTRAINT "backup_policies_minutoEjecucion_check" CHECK ("backup_policies"."minuto_ejecucion" >= 0 AND "backup_policies"."minuto_ejecucion" <= 59);
ALTER TABLE "backup_policies" ADD CONSTRAINT "backup_policies_diaSemana_check" CHECK ("backup_policies"."dia_semana" >= 1 AND "backup_policies"."dia_semana" <= 7);
ALTER TABLE "backup_policies" ADD CONSTRAINT "backup_policies_diaMes_check" CHECK ("backup_policies"."dia_mes" >= 1 AND "backup_policies"."dia_mes" <= 31);
ALTER TABLE "backup_policies" ADD CONSTRAINT "backup_policies_retencionDias_check" CHECK ("backup_policies"."retencion_dias" >= 0);
ALTER TABLE "backup_policies" ADD CONSTRAINT "backup_policies_maxBackups_check" CHECK ("backup_policies"."max_backups" >= 0);
ALTER TABLE "commission_records" ADD CONSTRAINT "commission_records_laborAmount_check" CHECK ("commission_records"."labor_amount" >= 0);
ALTER TABLE "commission_records" ADD CONSTRAINT "commission_records_commissionRate_check" CHECK ("commission_records"."commission_rate" BETWEEN 0 AND 100);
ALTER TABLE "commission_records" ADD CONSTRAINT "commission_records_commissionAmount_check" CHECK ("commission_records"."commission_amount" >= 0);
ALTER TABLE "control_herramientas" ADD CONSTRAINT "control_herramientas_costoReparacion_check" CHECK ("control_herramientas"."costo_reparacion" >= 0);
ALTER TABLE "cost_history" ADD CONSTRAINT "cost_history_cantidadAnterior_check" CHECK ("cost_history"."cantidad_anterior" >= 0);
ALTER TABLE "cost_history" ADD CONSTRAINT "cost_history_cantidadNueva_check" CHECK ("cost_history"."cantidad_nueva" >= 0);
ALTER TABLE "cost_history" ADD CONSTRAINT "cost_history_cantidadFinal_check" CHECK ("cost_history"."cantidad_final" >= 0);
ALTER TABLE "cost_history" ADD CONSTRAINT "cost_history_costoUnitarioNuevo_check" CHECK ("cost_history"."costo_unitario_nuevo" >= 0);
ALTER TABLE "depreciacion_activos" ADD CONSTRAINT "depreciacion_activos_montoDepreciacion_check" CHECK ("depreciacion_activos"."monto_depreciacion" >= 0);
ALTER TABLE "factura_detalles" ADD CONSTRAINT "factura_detalles_cantidad_check" CHECK ("factura_detalles"."cantidad" >= 0);
ALTER TABLE "factura_detalles" ADD CONSTRAINT "factura_detalles_precioUnitario_check" CHECK ("factura_detalles"."precio_unitario" >= 0);
ALTER TABLE "factura_detalles" ADD CONSTRAINT "factura_detalles_iva_check" CHECK ("factura_detalles"."iva" BETWEEN 0 AND 100);
ALTER TABLE "factura_detalles" ADD CONSTRAINT "factura_detalles_subtotal_check" CHECK ("factura_detalles"."subtotal" >= 0);
ALTER TABLE "facturas" ADD CONSTRAINT "facturas_total_check" CHECK ("facturas"."total" >= 0);
ALTER TABLE "facturas" ADD CONSTRAINT "facturas_saldoPendiente_check" CHECK ("facturas"."saldo_pendiente" >= 0);
ALTER TABLE "facturas_proveedor" ADD CONSTRAINT "facturas_proveedor_total_check" CHECK ("facturas_proveedor"."total" >= 0);
ALTER TABLE "facturas_proveedor" ADD CONSTRAINT "facturas_proveedor_saldoPendiente_check" CHECK ("facturas_proveedor"."saldo_pendiente" >= 0);
ALTER TABLE "facturas_proveedor" ADD CONSTRAINT "facturas_proveedor_baseImponible_check" CHECK ("facturas_proveedor"."base_imponible" >= 0);
ALTER TABLE "fiscal_documento_detalles" ADD CONSTRAINT "fiscal_documento_detalles_cantidad_check" CHECK ("fiscal_documento_detalles"."cantidad" >= 0);
ALTER TABLE "fiscal_documento_detalles" ADD CONSTRAINT "fiscal_documento_detalles_precioUnitario_check" CHECK ("fiscal_documento_detalles"."precio_unitario" >= 0);
ALTER TABLE "fiscal_documento_detalles" ADD CONSTRAINT "fiscal_documento_detalles_iva_check" CHECK ("fiscal_documento_detalles"."iva" BETWEEN 0 AND 100);
ALTER TABLE "fiscal_documento_detalles" ADD CONSTRAINT "fiscal_documento_detalles_subtotal_check" CHECK ("fiscal_documento_detalles"."subtotal" >= 0);
ALTER TABLE "fiscal_documentos" ADD CONSTRAINT "fiscal_documentos_totalExento_check" CHECK ("fiscal_documentos"."total_exento" >= 0);
ALTER TABLE "fiscal_documentos" ADD CONSTRAINT "fiscal_documentos_totalIva5_check" CHECK ("fiscal_documentos"."total_iva_5" >= 0);
ALTER TABLE "fiscal_documentos" ADD CONSTRAINT "fiscal_documentos_totalIva10_check" CHECK ("fiscal_documentos"."total_iva_10" >= 0);
ALTER TABLE "fiscal_documentos" ADD CONSTRAINT "fiscal_documentos_totalLiquido_check" CHECK ("fiscal_documentos"."total_liquido" >= 0);
ALTER TABLE "fiscal_documentos" ADD CONSTRAINT "fiscal_documentos_totalIva_check" CHECK ("fiscal_documentos"."total_iva" >= 0);
ALTER TABLE "fiscal_documentos" ADD CONSTRAINT "fiscal_documentos_totalDocumento_check" CHECK ("fiscal_documentos"."total_documento" >= 0);
ALTER TABLE "herramientas" ADD CONSTRAINT "herramientas_costoReposicion_check" CHECK ("herramientas"."costo_reposicion" >= 0);
ALTER TABLE "initial_inventory_loads" ADD CONSTRAINT "initial_inventory_loads_cantidad_check" CHECK ("initial_inventory_loads"."cantidad" >= 0);
ALTER TABLE "initial_inventory_loads" ADD CONSTRAINT "initial_inventory_loads_valorUnitario_check" CHECK ("initial_inventory_loads"."valor_unitario" >= 0);
ALTER TABLE "initial_inventory_loads" ADD CONSTRAINT "initial_inventory_loads_valorTotal_check" CHECK ("initial_inventory_loads"."valor_total" >= 0);
ALTER TABLE "label_templates" ADD CONSTRAINT "label_templates_dpi_check" CHECK ("label_templates"."dpi" >= 0);
ALTER TABLE "label_templates" ADD CONSTRAINT "label_templates_anchoMm_check" CHECK ("label_templates"."ancho_mm" >= 0);
ALTER TABLE "label_templates" ADD CONSTRAINT "label_templates_altoMm_check" CHECK ("label_templates"."alto_mm" >= 0);
ALTER TABLE "label_templates" ADD CONSTRAINT "label_templates_copiasDefault_check" CHECK ("label_templates"."copias_default" >= 0);
ALTER TABLE "liquidaciones_idu" ADD CONSTRAINT "liquidaciones_idu_tasaAplicada_check" CHECK ("liquidaciones_idu"."tasa_aplicada" BETWEEN 0 AND 100);
ALTER TABLE "liquidaciones_idu" ADD CONSTRAINT "liquidaciones_idu_porcentajeDistribuido_check" CHECK ("liquidaciones_idu"."porcentaje_distribuido" BETWEEN 0 AND 100);
ALTER TABLE "liquidaciones_idu" ADD CONSTRAINT "liquidaciones_idu_utilidadEfectiva_check" CHECK ("liquidaciones_idu"."utilidad_efectiva" BETWEEN 0 AND 100);
ALTER TABLE "liquidaciones_inr" ADD CONSTRAINT "liquidaciones_inr_montoBruto_check" CHECK ("liquidaciones_inr"."monto_bruto" >= 0);
ALTER TABLE "liquidaciones_inr" ADD CONSTRAINT "liquidaciones_inr_tasaRetencion_check" CHECK ("liquidaciones_inr"."tasa_retencion" BETWEEN 0 AND 100);
ALTER TABLE "liquidaciones_ire" ADD CONSTRAINT "liquidaciones_ire_costoRepuestos_check" CHECK ("liquidaciones_ire"."costo_repuestos" >= 0);
ALTER TABLE "liquidaciones_ire" ADD CONSTRAINT "liquidaciones_ire_costoManoObra_check" CHECK ("liquidaciones_ire"."costo_mano_obra" >= 0);
ALTER TABLE "liquidaciones_ire" ADD CONSTRAINT "liquidaciones_ire_totalCostos_check" CHECK ("liquidaciones_ire"."total_costos" >= 0);
ALTER TABLE "liquidaciones_ire" ADD CONSTRAINT "liquidaciones_ire_totalGastos_check" CHECK ("liquidaciones_ire"."total_gastos" >= 0);
ALTER TABLE "liquidaciones_isc" ADD CONSTRAINT "liquidaciones_isc_cantidad_check" CHECK ("liquidaciones_isc"."cantidad" >= 0);
ALTER TABLE "liquidaciones_isc" ADD CONSTRAINT "liquidaciones_isc_baseImponible_check" CHECK ("liquidaciones_isc"."base_imponible" >= 0);
ALTER TABLE "liquidaciones_iva" ADD CONSTRAINT "liquidaciones_iva_prorrateoIndice_check" CHECK ("liquidaciones_iva"."prorrateo_indice" BETWEEN 0 AND 100);
ALTER TABLE "mechanic_profiles" ADD CONSTRAINT "mechanic_profiles_baseSalary_check" CHECK ("mechanic_profiles"."base_salary" >= 0);
ALTER TABLE "mechanic_profiles" ADD CONSTRAINT "mechanic_profiles_commissionRate_check" CHECK ("mechanic_profiles"."commission_rate" BETWEEN 0 AND 100);
ALTER TABLE "movimientos_tesoreria" ADD CONSTRAINT "movimientos_tesoreria_monto_check" CHECK ("movimientos_tesoreria"."monto" >= 0);
ALTER TABLE "orden_repuestos" ADD CONSTRAINT "orden_repuestos_cantidad_check" CHECK ("orden_repuestos"."cantidad" >= 0);
ALTER TABLE "orden_repuestos" ADD CONSTRAINT "orden_repuestos_precioUnitario_check" CHECK ("orden_repuestos"."precio_unitario" >= 0);
ALTER TABLE "orden_repuestos" ADD CONSTRAINT "orden_repuestos_subtotal_check" CHECK ("orden_repuestos"."subtotal" >= 0);
ALTER TABLE "orden_servicios" ADD CONSTRAINT "orden_servicios_cantidad_check" CHECK ("orden_servicios"."cantidad" >= 0);
ALTER TABLE "orden_servicios" ADD CONSTRAINT "orden_servicios_precioUnitario_check" CHECK ("orden_servicios"."precio_unitario" >= 0);
ALTER TABLE "orden_servicios" ADD CONSTRAINT "orden_servicios_subtotal_check" CHECK ("orden_servicios"."subtotal" >= 0);
ALTER TABLE "presupuestos_items" ADD CONSTRAINT "presupuestos_items_montoPresupuestado_check" CHECK ("presupuestos_items"."monto_presupuestado" >= 0);
ALTER TABLE "presupuestos_items" ADD CONSTRAINT "presupuestos_items_montoReal_check" CHECK ("presupuestos_items"."monto_real" >= 0);
ALTER TABLE "print_jobs" ADD CONSTRAINT "print_jobs_copias_check" CHECK ("print_jobs"."copias" >= 0);
ALTER TABLE "purchase_order_items" ADD CONSTRAINT "purchase_order_items_cantidad_check" CHECK ("purchase_order_items"."cantidad" >= 0);
ALTER TABLE "purchase_order_items" ADD CONSTRAINT "purchase_order_items_cantidadRecibida_check" CHECK ("purchase_order_items"."cantidad_recibida" >= 0);
ALTER TABLE "purchase_order_items" ADD CONSTRAINT "purchase_order_items_costoUnitario_check" CHECK ("purchase_order_items"."costo_unitario" >= 0);
ALTER TABLE "purchase_order_items" ADD CONSTRAINT "purchase_order_items_subtotal_check" CHECK ("purchase_order_items"."subtotal" >= 0);
ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_totalOc_check" CHECK ("purchase_orders"."total_oc" >= 0);
ALTER TABLE "reorder_alerts" ADD CONSTRAINT "reorder_alerts_stockActual_check" CHECK ("reorder_alerts"."stock_actual" >= 0);
ALTER TABLE "reorder_alerts" ADD CONSTRAINT "reorder_alerts_puntoReorden_check" CHECK ("reorder_alerts"."punto_reorden" >= 0);
ALTER TABLE "repuestos" ADD CONSTRAINT "repuestos_precioCosto_check" CHECK ("repuestos"."precio_costo" >= 0);
ALTER TABLE "repuestos" ADD CONSTRAINT "repuestos_costoPromedio_check" CHECK ("repuestos"."costo_promedio" >= 0);
ALTER TABLE "repuestos" ADD CONSTRAINT "repuestos_precioVenta_check" CHECK ("repuestos"."precio_venta" >= 0);
ALTER TABLE "repuestos" ADD CONSTRAINT "repuestos_stockActual_check" CHECK ("repuestos"."stock_actual" >= 0);
ALTER TABLE "repuestos" ADD CONSTRAINT "repuestos_stockMinimo_check" CHECK ("repuestos"."stock_minimo" >= 0);
ALTER TABLE "repuestos" ADD CONSTRAINT "repuestos_stockMaximo_check" CHECK ("repuestos"."stock_maximo" >= 0);
ALTER TABLE "repuestos" ADD CONSTRAINT "repuestos_puntoReorden_check" CHECK ("repuestos"."punto_reorden" >= 0);
ALTER TABLE "repuestos" ADD CONSTRAINT "repuestos_loteEconomico_check" CHECK ("repuestos"."lote_economico" >= 0);
ALTER TABLE "restore_sessions" ADD CONSTRAINT "restore_sessions_progreso_check" CHECK ("restore_sessions"."progreso" BETWEEN 0 AND 100);
ALTER TABLE "service_pricing_rules" ADD CONSTRAINT "service_pricing_rules_precioVentaPyg_check" CHECK ("service_pricing_rules"."precio_venta_pyg" >= 0);
ALTER TABLE "service_pricing_rules" ADD CONSTRAINT "service_pricing_rules_precioCostoPyg_check" CHECK ("service_pricing_rules"."precio_costo_pyg" >= 0);
ALTER TABLE "service_pricing_rules" ADD CONSTRAINT "service_pricing_rules_impuestoIvaPct_check" CHECK ("service_pricing_rules"."impuesto_iva_pct" BETWEEN 0 AND 100);
ALTER TABLE "servicios_catalogo" ADD CONSTRAINT "servicios_catalogo_precioEstimado_check" CHECK ("servicios_catalogo"."precio_estimado" >= 0);
ALTER TABLE "sifen_sync_log" ADD CONSTRAINT "sifen_sync_log_duracionMs_check" CHECK ("sifen_sync_log"."duracion_ms" >= 0);
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_cantidad_check" CHECK ("stock_movements"."cantidad" >= 0);
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_stockAnterior_check" CHECK ("stock_movements"."stock_anterior" >= 0);
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_stockPosterior_check" CHECK ("stock_movements"."stock_posterior" >= 0);
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_costoUnitario_check" CHECK ("stock_movements"."costo_unitario" >= 0);
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_costoTotal_check" CHECK ("stock_movements"."costo_total" >= 0);
ALTER TABLE "tenant_config" ADD CONSTRAINT "tenant_config_cantidadPersonal_check" CHECK ("tenant_config"."cantidad_personal" >= 0);
ALTER TABLE "tool_depreciation_entries" ADD CONSTRAINT "tool_depreciation_entries_montoDepreciacion_check" CHECK ("tool_depreciation_entries"."monto_depreciacion" >= 0);
ALTER TABLE "tool_instances" ADD CONSTRAINT "tool_instances_costoAdquisicion_check" CHECK ("tool_instances"."costo_adquisicion" >= 0);

-- Migration complete — 103 CHECK constraints added.
