/**
 * Diagnostic Reports table — Drizzle ORM schema.
 *
 * Stores processed scanner reports and diagnostic results
 * generated by the Intelligence module's Launch/Thinkcar
 * DTC parser and OpenCode diagnostic engine.
 *
 * Each row represents a single scan session, linked to a vehicle
 * (FK → vehiculos) and optionally to a work order.
 *
 * RAM discipline: Drizzle schema metadata is negligible (~500B).
 * Actual report data (JSONB) is stored on remote PostgreSQL.
 *
 * @module intelligence/schema/diagnostic-reports
 */

import {
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { vehiculos } from "../../workshop/schema/vehiculos.js";
import { ordenesTrabajo } from "../../workshop/schema/ordenes-trabajo.js";

/**
 * Diagnostic Reports — full scan results from Launch/Thinkcar scanners.
 *
 * Stores:
 *   - Raw and parsed DTC data
 *   - Diagnostic engine findings
 *   - HV safety protocol references
 *   - Source report metadata (scanner brand, file name)
 */
export const diagnosticReports = pgTable("diagnostic_reports", {
  /** Primary key */
  id: uuid("id").primaryKey().defaultRandom(),

  /** FK → vehiculos (the vehicle that was scanned) */
  vehicleId: uuid("vehicle_id")
    .notNull()
    .references(() => vehiculos.id, { onDelete: "cascade" }),

  /** Optional FK → ordenes_trabajo */
  ordenTrabajoId: uuid("orden_trabajo_id")
    .references(() => ordenesTrabajo.id, { onDelete: "set null" }),

  /** Scanner brand/model (e.g. "Launch X431", "Thinkcar ThinkTool") */
  scannerBrand: text("scanner_brand"),

  /** Full parsed ScanReport as JSONB */
  scanReport: jsonb("scan_report"),

  /** OpenCode diagnostic result as JSONB */
  diagnosisResult: jsonb("diagnosis_result"),

  /** HV safety protocol as JSONB (if EV/HEV) */
  hvProtocol: jsonb("hv_protocol"),

  /** Odometer reading at scan time (km) */
  odometer: integer("odometer"),

  /** Number of DTCs found */
  dtcCount: integer("dtc_count").notNull().default(0),

  /** Number of critical DTCs */
  criticalCount: integer("critical_count").notNull().default(0),

  /** Whether HV safety protocol was generated */
  hvProtocolGenerated: text("hv_protocol_generated").default("no"),

  /** Free-text notes */
  notes: text("notes"),

  // ─── Timestamps ───────────────────────────
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// ─── Types ─────────────────────────────────────

/** Row type returned by SELECT */
export type DiagnosticReport = typeof diagnosticReports.$inferSelect;

/** Row type accepted by INSERT */
export type NewDiagnosticReport = typeof diagnosticReports.$inferInsert;
